# More syntax details at: https://docs.travis-ci.com/user/customizing-the-build
# copy from pyscf project

language: python
os: 
  - linux
  # - osx

python:
  - 3.6

before_install:
  - uname -a

install:
  - pip install -r requirements.txt
  - pip install pandoc coverage twine

before_script:
  - python -V


script:
  - make build
  - make travisinstall
  - make test


